### ISSUE TITLE
High frequency updates on real-time charts

### ISSUE THREAD

**Issue by PHameete** [timmolter/XChart#209]
Hi,

we are looking for a charting library that can handle high frequency data updates in real-time. I've tried to test whether XChart is able to do this by making a modification to the realtime demo 3.

I've moved the updateData call to a separate TimerTask that runs every millisecond to add 1000 datapoints per second. The chart is still repainted every 500ms by another TimerTask. Unfortunately this results in a concurrent modification exception:

Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.knowm.xchart.internal.chartpart.PlotContent_XY.doPaint(PlotContent_XY.java:212)
	at org.knowm.xchart.internal.chartpart.PlotContent_.paint(PlotContent_.java:67)
	at org.knowm.xchart.internal.chartpart.Plot_.paint(Plot_.java:56)
	at org.knowm.xchart.internal.chartpart.Plot_AxesChart.paint(Plot_AxesChart.java:55)
	at org.knowm.xchart.XYChart.paint(XYChart.java:343)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:118)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Is XChart ment for this type of usage?

**Comment by timmolter** [comment]
Make sure to use `CopyOnWriteArrayList` instead of `ArrayList` exactly like in `RealtimeChart03`. It should work flawlessly.

**Comment by PHameete** [comment]
Correct. I believe I found the issue. In RealtimeChart function getChart() the xData and errorData are initialized with an `ArrayList` instead of a `CopyOnWriteArrayList`. This  is already the case in the demo code. It does not cause any issues if you update every 500 milliseconds, but with the timertask scheduled for each millisecond it will give the above issue.

**Comment by timmolter** [comment]
Ah good catch. I'll fix it.

There's no need to update a chart once per millisecond. Maybe try the second approach here: http://knowm.org/how-to-make-real-time-charts-in-java/ using a `Swingworker`.
