### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by seewip** [timmolter/XChart#81]
My app containing xchart will get the ConcurrentModificationException (as in the stacktrace below) once every few hours or when the computer wakes up from sleep/hibernation. The graph is a live area-chart updated each second.

Stacktrace:
```
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.xeiam.xchart.internal.chartpart.PlotContentLineChart.paint(PlotContentLineChart.java:117)
	at com.xeiam.xchart.internal.chartpart.Plot.paint(Plot.java:84)
	at com.xeiam.xchart.internal.chartpart.ChartPainter.paint(ChartPainter.java:111)
	at com.xeiam.xchart.internal.chartpart.ChartPainter.paint(ChartPainter.java:70)
	at com.xeiam.xchart.Chart.paint(Chart.java:94)
	at com.xeiam.xchart.XChartPanel.paintComponent(XChartPanel.java:89)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1300(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by rizwanali89** [comment]
Hi,
Seewip and timmolter....
I got the same situation.... After this error occur my java based GUI freez. when I minimize and then maximize any xchart or my java GUI jfram it get black no thing shown in GUI except black color.

**Comment by rizwanali89** [comment]
I thing there is a bug in xchart API we are using. Actually I rendered a graph based on values comes from server in fraction of  seconds.

**Comment by timmolter** [comment]
Use a `CopyOnWriteArrayList` to store your data rather than ArrayLists. I'll update the real-time demos.
